function python_background(){
    document.getElementById('body').className = "body_python";
} 

function js_background(){
    document.getElementById('body').className = "body_js";

} 

function html_background(){
    document.getElementById('body').className = "body_html";

} 

function css_background(){
    document.getElementById('body').className = "body_css";

} 

function message(message){
    alert(message)
}
